CREATE TABLE "users" (
  "id"         INTEGER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "name"       VARCHAR   NOT NULL,
  "email"      VARCHAR   NOT NULL,
  "password"   VARCHAR   NOT NULL,
  "created"    TIMESTAMP NOT NULL,
  "is_deleted" BOOLEAN   NOT NULL
);
CREATE TABLE "bills" (
  "id"              INTEGER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "place_id"        INTEGER        NOT NULL,
  "service_id"      INTEGER        NOT NULL,
  "service_rate_id" INTEGER        NOT NULL,
  "readout"         DECIMAL(21, 2) NOT NULL,
  "value_amount"    DECIMAL(21, 2) NOT NULL,
  "value_currency"  VARCHAR        NOT NULL,
  "created"         TIMESTAMP      NOT NULL,
  "paid"            TIMESTAMP,
  "is_deleted"      BOOLEAN        NOT NULL
);
CREATE TABLE "places" (
  "id"         INTEGER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "title"      VARCHAR NOT NULL,
  "country"    VARCHAR NOT NULL,
  "city"       VARCHAR NOT NULL,
  "state"      VARCHAR NOT NULL,
  "zip"        VARCHAR NOT NULL,
  "address"    VARCHAR NOT NULL,
  "is_deleted" BOOLEAN NOT NULL
);
CREATE TABLE "places_services" (
  "place_id"   INTEGER   NOT NULL,
  "service_id" INTEGER   NOT NULL,
  "created"    TIMESTAMP NOT NULL
);
ALTER TABLE "places_services"
  ADD CONSTRAINT "placeId_serviceId" PRIMARY KEY ("place_id", "service_id");
CREATE TABLE "service_rates" (
  "id"                 INTEGER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "service_id"         INTEGER   NOT NULL,
  "is_active"          BOOLEAN   NOT NULL,
  "active_from_date"   TIMESTAMP NOT NULL,
  "inactive_from_date" TIMESTAMP,
  "rate_data"          VARCHAR   NOT NULL,
  "is_deleted"         BOOLEAN   NOT NULL
);
CREATE TABLE "services" (
  "id"                 INTEGER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "title"              VARCHAR NOT NULL,
  "area"               VARCHAR NOT NULL,
  "description"        VARCHAR NOT NULL,
  "created_by_user_id" INTEGER NOT NULL,
  "is_deleted"         BOOLEAN NOT NULL
);
CREATE TABLE "users_places" (
  "user_id"  INTEGER NOT NULL,
  "place_id" INTEGER NOT NULL,
  "role"     VARCHAR NOT NULL
);
ALTER TABLE "users_places"
  ADD CONSTRAINT "userId_placeId" PRIMARY KEY ("user_id", "place_id");
